### ISSUE TITLE
ptls error on macos

### ISSUE THREAD

**Issue by RCPhysics** [jszczerbinsky/ptSh#23]
After installing on macOS and adding to ZSH path I receive the following error when running ptlsL

/Users/username/.local/bin/ptls: line 91: -1: substring expression < 0

**Comment by jszczerbinsky** [comment]
Describe a situation, when bug occurs

**Comment by jszczerbinsky** [comment]
Does it happen all the time?

**Comment by Jaysce** [comment]
This issue occurs because macOS ships with an outdated version of bash. Run `brew install bash` to get the latest version, then you won't get that error.

But you will still get problems running `ls` and `touch`, the other commands included with ptls will run fine.
`touch` doesn't work because macOS ships with the BSD version of `readlink` and not the GNU version. You can install the coreutils package using `brew install coreutils` and then replace `readlink` with `greadlink` in the file pttouch, which you can get to via `$HOME/.local/bin/pttouch`. Replace `readlink` with `greadlink` on line 29.

For the `ls` command it only displays the file icon for some reason. I haven't figured out how to fix it yet.

**Comment by jszczerbinsky** [comment]
`ls` probably writes something to `stderr`, but `stderr` is disabled.
Remove `2>/dev/null` from line 14 and 43 in `ptls` and show the output.

**Comment by jszczerbinsky** [comment]
I think it's problem with `--group-directories-first` in line 43

**Comment by Jaysce** [comment]
I just checked and its simply because macOS doesn't use GNU core utils, so there are some commands that don't work. The problem with `ls` was because its using the BSD version of `ls` which doesn't take in the argument `-Q`.
So the easiest way to fix this issue is this:
1. Install latest version of bash using `brew install bash`
2. Install core utils using `brew install coreutils`
3. Core utils provides the same commands prefixed with a 'g', so to use the GNU variants instead of the BSD variants, you can add the gnubin directory to your path by putting `export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"`, into your bashrc or zshrc.

Everything should work fine after that. No need to edit any of the ptsh files.
