### ISSUE TITLE
[BUG] ptls doesn't seem to use the path as an argument

### ISSUE THREAD

**Issue by creepinson** [jszczerbinsky/ptSh#28]
**Describe the bug**
I can't use ptls with a path as the first argument like ls...

**To Reproduce**
Run ptls with a folder at ~/test created:

```bash
ptls ~/test
```

**Expected behavior**
It shows the files in `~/test` instead of the current working directory.

**Screenshots/terminal output**
![image](https://user-images.githubusercontent.com/11761863/118201307-0156b900-b40c-11eb-8c90-b5fa22c9384e.png)

Here it shows the files from the cwd, `~/my-config`

**Desktop**
 - OS/Linux distro: [e.g. MacOS, ArchLinux, Debian]
I am running Manjaro.

**Comment by goddard-guryon** [comment]
Having the same issue on Arch. It also looks like `ptls` behaves strangely with any arguments at all. In my .bashrc, I had set `alias ls='ls --color=auto'` (which I changed to `'ptls --color=auto'` to match with the config). However, when I use `ls` now, it shows output of `ls -al`. If I type `ptls`, I get the desired output (only file/folder names and icons), but even `ptls --help` shows output like `ptls -l` (I get that there might be no `--help` available, but then it should just give an error), so it looks like it's unable to process any kind of argument, not just the path (like you specified).

![image](https://i.imgur.com/5xmcvzE.png)

**Comment by jszczerbinsky** [comment]
This script behaves strangely, because it has to run `ls` with these arguments, but some of them can totally change the output and then resulting output of `ptls` could be unpredictable.

I realised, that running commands by shell script and then customizing their output is not the point. Because of that  I'm now replacing `ptls` and other scripts with programs written  in C. They will take same arguments as original shell commands (or at least most of them) and produce ptls-like output. It will be better and less buggy solution. So be patient and wait a few days for new, better ptSh commands, with ability of processing all the arguments ;)

**Comment by jszczerbinsky** [comment]
Btw current `ptls` just ignores most of the arguments and this is a cause if these bugs

**Comment by goddard-guryon** [comment]
@jszczerbinsky I was trying to implement a few of those arguments into the shell script, but it seems I can't do that now since I don't know C ._. But great work still, I'd try to contribute in any way I can :)
