### ISSUE TITLE
[Feature proposal] Add cp + mv + rm

### ISSUE THREAD

**Issue by Ramiferous** [jszczerbinsky/ptSh#29]
I would love for you to add `cp` & `mv` and `rm` to the options. 
Specifically, it would be nice to have a progress bar for large file transfers with these options, much like in [advcpmv](https://github.com/jarun/advcpmv)

**Comment by jszczerbinsky** [comment]
It's very hard to create something like progress bar from output of running command in bash. I have plan to replace bash scripts with C programs, that will be as powerful as standard coreutils commands, but their output will be a lot prettier and customizable. I mean - create programs, that will produce colorful and customizable output, instead of running command from shell script and then customizing it's output.

I have plans to add progress bar to `ptcp` `ptmv` and `ptrm`
