### ISSUE TITLE
[BUG] ptls almostAll option makes some directories ungrouped

### ISSUE THREAD

**Issue by doongjohn** [jszczerbinsky/ptSh#55]
**Describe the bug**
ptls almostAll option makes some directories ungrouped

**To Reproduce**
ptls -lA

**Expected behavior**
![image](https://user-images.githubusercontent.com/40219740/162030079-10ff8c09-2288-4ad8-a366-5f1dbb68d384.png)

**Screenshots/terminal output**
![image](https://user-images.githubusercontent.com/40219740/162029846-224e052e-2f95-441c-ab5d-5e24fedf4440.png)

**Desktop**
 - Windows11/WSL2(Void linux)

**Workaround**
```c
  // src/ptls/main.c
  ...
  if(dirContent->fileCount >1)
  {
    // adding this code seems to fix the issue
    if (args->almostAll)
      dirCount += 2;

    if(args->noDirsTop)
      sort(dirContent->files, args, 0, dirContent->fileCount-1);
    else
    {
      groupDirs(dirContent, dirCount);
      sort(dirContent->files, args, 0, dirCount-1);
      sort(dirContent->files, args, dirCount, dirContent->fileCount-1);
    }
  }
  ...
```

**Comment by jszczerbinsky** [comment]
Adding `2` to `dirCount` works, when `ptls` is used with `--almost-all`, but I found, that bug was occuring in any situation where some dirs are hidden. I fixed it by adding all dirs to `dirCount`, not only visible ones.
Check out [v0.3.3-beta](https://github.com/jszczerbinsky/ptSh/releases/tag/v0.3.3-beta)
